# -*- coding: utf-8 -*-
"""001_표를 다루는 도구 - 판다스.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fr_dy3ZqK0H8wfre8CSmUzxSzgGTXONx
"""

# 판다스 라이브러리 읽어오기
import pandas as pd

# 파일로부터 데이터 읽어오기
레모네이드 = pd.read_csv('https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv')
보스턴 = pd.read_csv('https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv')
아이리스 = pd.read_csv('https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv')

# 데이터 모양으로 확인하기
print(레모네이드.shape)
print(보스턴.shape)
print(아이리스.shape)

# 칼럼이름 출력
print(레모네이드.columns)
print(보스턴.columns)
print(아이리스.columns)

# 독립변수 & 종속변수 분리하기
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종']]
print(독립.shape, 종속.shape)

# 상위 5개 데이터 출력해보기
레모네이드.head()
보스턴.head()
아이리스.head()

