# -*- coding: utf-8 -*-
"""006_원핫인코딩&결측처리.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14V-xJV_krGxFMwYwlv2Hu42VGK8RzsiK

# 데이터 타입 조정
https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris2.csv

- **원핫인코딩 시 문제**
  - 변수(칼럼) 타입 확인: `데이터.dtypes`
  - 변수를 범주형으로 변경:
    - `데이터['칼럼명'].astype('category')`
  - 변수를 수치형으로 변경:
    - `데이터['칼럼명'].astype('int')`
    - `데이터['칼럼명'].astype('float')`
- **결측치 처리방법**
  - NA 값의 처리
    - NA 갯수 체크: `데이터.isna().sum()`
    - NA 값 채우기: `데이터['칼럼명'].fillna(특정값)`
"""

# 라이브러리
import pandas as pd

아이리스 = pd.read_csv('https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris2.csv')
아이리스.head()

# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

# 데이터 타입 체크
아이리스.dtypes

# 품종 타입을 범주형으로 바꾸어 준다.
아이리스['품종'] = 아이리스['품종'].astype('category') # int64 -> category 로 바꿔야 원핫인코딩 가능
아이리스.dtypes

# 다시 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

# NA값을 체크해 봅시다.
아이리스.isna().sum()

아이리스.tail()

# NA 결측치를 바꾸어주거나, 행을 삭제시켜준다.
# 1. NA값에 꽃잎폭 평균값을 넣어주는 방법
mean = 아이리스['꽃잎폭'].mean()
print(mean)
아이리스['꽃잎폭'] = 아이리스['꽃잎폭'].fillna(mean)
아이리스.tail()

